{
  "formatVersion": "1.1",
  "component": {
    "group": "org.sinytra.forgified-fabric-api",
    "module": "fabric-lifecycle-events-v1",
    "version": "4.1.4+d89c76349e",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "2.0.4+d41ec0009e"
          }
        }
      ],
      "files": [
        {
          "name": "fabric-lifecycle-events-v1-4.1.4+d89c76349e.jar",
          "url": "fabric-lifecycle-events-v1-4.1.4+d89c76349e.jar",
          "size": 103257,
          "sha512": "929727ad5288a57e44342db0adf7fb179de560c8fbe228855f1e7ebef4ca1d58ef8a6ea0fda3a8766ac996cf7733ff0a8fa4b371238c81ee0fcafb396e3c1c5d",
          "sha256": "adc588a9f7a6f61aee38a1d7f11a958dbc84c608f5eabbefc5897f13cdc43fb2",
          "sha1": "7a01d9cd40f668b230da1fe78b6cab4ae8157549",
          "md5": "4decd84e005be27d9fbe88f5cbea7293"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.sinytra",
          "module": "forgified-fabric-loader",
          "version": {
            "requires": "2.5.83+0.19.3+26.1.2"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "2.0.4+d41ec0009e"
          }
        }
      ],
      "files": [
        {
          "name": "fabric-lifecycle-events-v1-4.1.4+d89c76349e.jar",
          "url": "fabric-lifecycle-events-v1-4.1.4+d89c76349e.jar",
          "size": 103257,
          "sha512": "929727ad5288a57e44342db0adf7fb179de560c8fbe228855f1e7ebef4ca1d58ef8a6ea0fda3a8766ac996cf7733ff0a8fa4b371238c81ee0fcafb396e3c1c5d",
          "sha256": "adc588a9f7a6f61aee38a1d7f11a958dbc84c608f5eabbefc5897f13cdc43fb2",
          "sha1": "7a01d9cd40f668b230da1fe78b6cab4ae8157549",
          "md5": "4decd84e005be27d9fbe88f5cbea7293"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "fabric-lifecycle-events-v1-4.1.4+d89c76349e-accesstransformer.cfg",
          "url": "fabric-lifecycle-events-v1-4.1.4+d89c76349e-accesstransformer.cfg",
          "size": 207,
          "sha512": "617824c13f5aaa2e9710bcd8ffff6d999cd7380e17490ab2264fbb1d79ea9c4e36b548b915dfe35429d405355f0d503a8d152c290d9710f8bbd363f31d8a95a4",
          "sha256": "091c1c6a004810b9627f7adde650dc79086568947d8784d2abc61009c9e5e6e1",
          "sha1": "488c4f1f6584934b0b619744ae46ac1008fe9c37",
          "md5": "9babe01541c66c167f9d87a24f51c1d4"
        }
      ]
    },
    {
      "name": "interfaceInjectionDataElements",
      "attributes": {
        "org.gradle.category": "interfaceinjection"
      },
      "files": [
        {
          "name": "fabric-lifecycle-events-v1-4.1.4+d89c76349e-interfaceinjection.json",
          "url": "fabric-lifecycle-events-v1-4.1.4+d89c76349e-interfaceinjection.json",
          "size": 112,
          "sha512": "6b004687357ec315edc8106c6dddce8b3264f95a79c10109171a394962fc3fb498ed540ad00ea77a18d488285a3364e5e4fd1c00c37751961e6569de314764c5",
          "sha256": "78cf3754d32cda13d9f30d2c7696661b39ac8e4ca5bc17e38382eac3ccfb9868",
          "sha1": "6ae5f1ce8301cdbbb045c758401b8e764dd56b35",
          "md5": "24a6b4290f94b1db76ebdaeca631e5d0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fabric-lifecycle-events-v1-4.1.4+d89c76349e-sources.jar",
          "url": "fabric-lifecycle-events-v1-4.1.4+d89c76349e-sources.jar",
          "size": 62551,
          "sha512": "3fb4193ab7a3efaa24fd901cfd7cc8a54f1f48480b44bcbf6a8e163e1e6f2066ec2bb53cc0261d5ee35694a08e44ba4e8181cef8a6172dd1ced19bb7de99da6a",
          "sha256": "7318f8add534a04b0ad4d4b0244b19fc35aac038472ed7ad123d07f3f4bb4083",
          "sha1": "0e8d189452066f4cf0d99315e6da10bc56edd7fd",
          "md5": "cfa30ecfea63a8f20deae68eab3c595d"
        }
      ]
    }
  ]
}
