{
  "formatVersion": "1.1",
  "component": {
    "group": "org.sinytra.forgified-fabric-api",
    "module": "forgified-fabric-api",
    "version": "0.159.0+26.2+4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.sinytra",
          "module": "forgified-fabric-loader",
          "version": {
            "requires": "2.5.83+0.19.3+26.1.2"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "2.0.4+d41ec0009e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-api-lookup-api-v1",
          "version": {
            "requires": "2.0.18+5f5192e39e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-biome-api-v1",
          "version": {
            "requires": "18.0.6+5f5192e39e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-block-api-v1",
          "version": {
            "requires": "3.0.3+12da5b389e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-block-getter-api-v2",
          "version": {
            "requires": "2.0.7+ec56b6019e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-client-gametest-api-v1",
          "version": {
            "requires": "6.0.1+3245a3939e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "3.1.0+df4186689e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-content-registries-v0",
          "version": {
            "requires": "11.3.2+3731f8bf9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-convention-tags-v2",
          "version": {
            "requires": "4.7.1+33362aa29e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-creative-tab-api-v1",
          "version": {
            "requires": "5.0.14+930083f69e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-data-attachment-api-v1",
          "version": {
            "requires": "2.2.18+203ddbf49e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-data-generation-api-v1",
          "version": {
            "requires": "25.5.1+3245a3939e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-debug-api-v1",
          "version": {
            "requires": "1.0.2+2b0337649e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-dimensions-v1",
          "version": {
            "requires": "5.1.12+df4186689e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-entity-events-v1",
          "version": {
            "requires": "5.0.5+306652609e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-events-interaction-v0",
          "version": {
            "requires": "5.2.7+df4186689e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-game-rule-api-v1",
          "version": {
            "requires": "4.0.8+46a6d00c9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-gametest-api-v1",
          "version": {
            "requires": "4.0.21+905131659e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-item-api-v1",
          "version": {
            "requires": "14.5.0+306652609e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-key-mapping-api-v1",
          "version": {
            "requires": "2.0.5+ce13d5789e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "4.1.4+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-loot-api-v3",
          "version": {
            "requires": "3.0.17+8472aabc9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-menu-api-v1",
          "version": {
            "requires": "2.0.16+445199e59e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-message-api-v1",
          "version": {
            "requires": "7.0.8+bb2ed3f79e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-model-loading-api-v1",
          "version": {
            "requires": "8.0.17+306652609e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "6.3.3+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-object-builder-api-v1",
          "version": {
            "requires": "24.1.0+306652609e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-particles-v1",
          "version": {
            "requires": "5.0.18+35e09eec9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-permission-api-v1",
          "version": {
            "requires": "1.0.5+b8759c2f9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-recipe-api-v1",
          "version": {
            "requires": "9.0.21+5bc850709e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "7.1.0+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-renderer-api-v1",
          "version": {
            "requires": "14.1.4+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-renderer-indigo",
          "version": {
            "requires": "9.1.4+dfc0a2a19e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-rendering-fluids-v1",
          "version": {
            "requires": "6.0.4+2252655c9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-rendering-v1",
          "version": {
            "requires": "25.3.3+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-resource-conditions-api-v1",
          "version": {
            "requires": "6.1.0+0404dc439e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-resource-loader-v1",
          "version": {
            "requires": "2.0.13+60fb9d7f9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-screen-api-v1",
          "version": {
            "requires": "5.2.1+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-serialization-api-v1",
          "version": {
            "requires": "2.0.4+877e9f519e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-sound-api-v1",
          "version": {
            "requires": "2.0.5+76b071469e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-tag-api-v1",
          "version": {
            "requires": "2.1.4+33362aa29e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-transfer-api-v1",
          "version": {
            "requires": "8.0.13+d6727f829e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-transitive-access-wideners-v1",
          "version": {
            "requires": "8.1.4+3b084dff9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "3.3.20+5f5192e39e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "ffapi-fluid-types",
          "version": {
            "requires": "1.1.0+746500be9e"
          }
        }
      ],
      "files": [
        {
          "name": "forgified-fabric-api-0.159.0+26.2+4.0.0.jar",
          "url": "forgified-fabric-api-0.159.0+26.2+4.0.0.jar",
          "size": 2986846,
          "sha512": "2420fc05fb0ea6411d144887616df80218cc510d8ba2fafefe9148585103d368590f481c35766afff938c082a7f7477ccef9685a6db921046587dad3c669c63f",
          "sha256": "698738be956d693746cb1b561728310c13d0942a5a7d908795cf16849b48579b",
          "sha1": "4086f179522f5b361ed3a498b035560c2a9c89b8",
          "md5": "39d0aa6f974a291e34d0753593e503cf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.sinytra",
          "module": "forgified-fabric-loader",
          "version": {
            "requires": "2.5.83+0.19.3+26.1.2"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "2.0.4+d41ec0009e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-api-lookup-api-v1",
          "version": {
            "requires": "2.0.18+5f5192e39e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-biome-api-v1",
          "version": {
            "requires": "18.0.6+5f5192e39e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-block-api-v1",
          "version": {
            "requires": "3.0.3+12da5b389e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-block-getter-api-v2",
          "version": {
            "requires": "2.0.7+ec56b6019e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-client-gametest-api-v1",
          "version": {
            "requires": "6.0.1+3245a3939e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "3.1.0+df4186689e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-content-registries-v0",
          "version": {
            "requires": "11.3.2+3731f8bf9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-convention-tags-v2",
          "version": {
            "requires": "4.7.1+33362aa29e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-creative-tab-api-v1",
          "version": {
            "requires": "5.0.14+930083f69e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-data-attachment-api-v1",
          "version": {
            "requires": "2.2.18+203ddbf49e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-data-generation-api-v1",
          "version": {
            "requires": "25.5.1+3245a3939e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-debug-api-v1",
          "version": {
            "requires": "1.0.2+2b0337649e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-dimensions-v1",
          "version": {
            "requires": "5.1.12+df4186689e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-entity-events-v1",
          "version": {
            "requires": "5.0.5+306652609e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-events-interaction-v0",
          "version": {
            "requires": "5.2.7+df4186689e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-game-rule-api-v1",
          "version": {
            "requires": "4.0.8+46a6d00c9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-gametest-api-v1",
          "version": {
            "requires": "4.0.21+905131659e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-item-api-v1",
          "version": {
            "requires": "14.5.0+306652609e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-key-mapping-api-v1",
          "version": {
            "requires": "2.0.5+ce13d5789e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "4.1.4+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-loot-api-v3",
          "version": {
            "requires": "3.0.17+8472aabc9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-menu-api-v1",
          "version": {
            "requires": "2.0.16+445199e59e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-message-api-v1",
          "version": {
            "requires": "7.0.8+bb2ed3f79e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-model-loading-api-v1",
          "version": {
            "requires": "8.0.17+306652609e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "6.3.3+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-object-builder-api-v1",
          "version": {
            "requires": "24.1.0+306652609e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-particles-v1",
          "version": {
            "requires": "5.0.18+35e09eec9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-permission-api-v1",
          "version": {
            "requires": "1.0.5+b8759c2f9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-recipe-api-v1",
          "version": {
            "requires": "9.0.21+5bc850709e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "7.1.0+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-renderer-api-v1",
          "version": {
            "requires": "14.1.4+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-renderer-indigo",
          "version": {
            "requires": "9.1.4+dfc0a2a19e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-rendering-fluids-v1",
          "version": {
            "requires": "6.0.4+2252655c9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-rendering-v1",
          "version": {
            "requires": "25.3.3+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-resource-conditions-api-v1",
          "version": {
            "requires": "6.1.0+0404dc439e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-resource-loader-v1",
          "version": {
            "requires": "2.0.13+60fb9d7f9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-screen-api-v1",
          "version": {
            "requires": "5.2.1+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-serialization-api-v1",
          "version": {
            "requires": "2.0.4+877e9f519e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-sound-api-v1",
          "version": {
            "requires": "2.0.5+76b071469e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-tag-api-v1",
          "version": {
            "requires": "2.1.4+33362aa29e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-transfer-api-v1",
          "version": {
            "requires": "8.0.13+d6727f829e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-transitive-access-wideners-v1",
          "version": {
            "requires": "8.1.4+3b084dff9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "3.3.20+5f5192e39e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "ffapi-fluid-types",
          "version": {
            "requires": "1.1.0+746500be9e"
          }
        }
      ],
      "files": [
        {
          "name": "forgified-fabric-api-0.159.0+26.2+4.0.0.jar",
          "url": "forgified-fabric-api-0.159.0+26.2+4.0.0.jar",
          "size": 2986846,
          "sha512": "2420fc05fb0ea6411d144887616df80218cc510d8ba2fafefe9148585103d368590f481c35766afff938c082a7f7477ccef9685a6db921046587dad3c669c63f",
          "sha256": "698738be956d693746cb1b561728310c13d0942a5a7d908795cf16849b48579b",
          "sha1": "4086f179522f5b361ed3a498b035560c2a9c89b8",
          "md5": "39d0aa6f974a291e34d0753593e503cf"
        }
      ]
    },
    {
      "name": "accessTransformersElements",
      "attributes": {
        "org.gradle.category": "accesstransformer"
      },
      "files": [
        {
          "name": "forgified-fabric-api-0.159.0+26.2+4.0.0-accesstransformer.accesstransformer",
          "url": "forgified-fabric-api-0.159.0+26.2+4.0.0-accesstransformer.accesstransformer",
          "size": 128188,
          "sha512": "c1ef96d519eb1c47368ea4bca7ffeb361bb9224dda69dc4cecba7ec5ee03fb45a11f698cc08cd7343012b284bd5c8efd201f0c0a20114813972c63dded0f0c40",
          "sha256": "6eb71d0c23173003e552282aba8519f284c6c6a1fca675cd0afc3d951852f69d",
          "sha1": "b363916ffd19ba6606a50694ffa0484e0fc45cc2",
          "md5": "9c57cc523dbb8cfaa7ea315a49e1e5ce"
        }
      ]
    },
    {
      "name": "interfaceInjectionDataElements",
      "attributes": {
        "org.gradle.category": "interfaceinjection"
      },
      "files": [
        {
          "name": "forgified-fabric-api-0.159.0+26.2+4.0.0-interfaceinjection.json",
          "url": "forgified-fabric-api-0.159.0+26.2+4.0.0-interfaceinjection.json",
          "size": 11725,
          "sha512": "bbec601c2b027f7c4abf9ebb7b3b6b0e9f218403d3d3ae91a3783347a6f07078dc340cb780e530a31550da943b024f624f53f6cbd9548815f45019f3e65f0d27",
          "sha256": "19b5c949d031e7b4b13ab5d95caa0db1e0283907cb6e10736da9bce839948465",
          "sha1": "ea64ed7cceb48d9a64e551677977a47a224a5fbb",
          "md5": "4e5b4b500a4ea9808de7cf3a222b54b8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "forgified-fabric-api-0.159.0+26.2+4.0.0-sources.jar",
          "url": "forgified-fabric-api-0.159.0+26.2+4.0.0-sources.jar",
          "size": 13402,
          "sha512": "da203e0e4ec2a5066e92f8ff5383c76760fd532a6f071ac7b6de1454385b722b5873481ce84d65490fe61d9dd2c19724fc0e455efbb2ee90b04a64810099851a",
          "sha256": "ced1abf40b2e68161707dcd13603d8cbeadd691fe4434cb9120fba1fff22ab74",
          "sha1": "1bd8005a2f2f6f0120a98307a020d4142ccb5c39",
          "md5": "6b2dee28cc68f1fd9afcfd149f5388c7"
        }
      ]
    }
  ]
}
