{
  "formatVersion": "1.1",
  "component": {
    "group": "org.sinytra.forgified-fabric-api",
    "module": "fabric-api-bom",
    "version": "0.159.0+26.2+4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-api"
      },
      "dependencyConstraints": [
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "forgified-fabric-api",
          "version": {
            "requires": "0.159.0+26.2+4.0.0"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-api-deprecated",
          "version": {
            "requires": "0.159.0+26.2+4.0.0"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "2.0.4+d41ec0009e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-api-lookup-api-v1",
          "version": {
            "requires": "2.0.18+5f5192e39e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-biome-api-v1",
          "version": {
            "requires": "18.0.6+5f5192e39e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-block-api-v1",
          "version": {
            "requires": "3.0.3+12da5b389e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-block-getter-api-v2",
          "version": {
            "requires": "2.0.7+ec56b6019e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-client-gametest-api-v1",
          "version": {
            "requires": "6.0.1+3245a3939e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "3.1.0+df4186689e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-content-registries-v0",
          "version": {
            "requires": "11.3.2+3731f8bf9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-convention-tags-v2",
          "version": {
            "requires": "4.7.1+33362aa29e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-creative-tab-api-v1",
          "version": {
            "requires": "5.0.14+930083f69e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-data-attachment-api-v1",
          "version": {
            "requires": "2.2.18+203ddbf49e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-data-generation-api-v1",
          "version": {
            "requires": "25.5.1+3245a3939e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-debug-api-v1",
          "version": {
            "requires": "1.0.2+2b0337649e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-dimensions-v1",
          "version": {
            "requires": "5.1.12+df4186689e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-entity-events-v1",
          "version": {
            "requires": "5.0.5+306652609e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-events-interaction-v0",
          "version": {
            "requires": "5.2.7+df4186689e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-game-rule-api-v1",
          "version": {
            "requires": "4.0.8+46a6d00c9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-gametest-api-v1",
          "version": {
            "requires": "4.0.21+905131659e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-item-api-v1",
          "version": {
            "requires": "14.5.0+306652609e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-key-mapping-api-v1",
          "version": {
            "requires": "2.0.5+ce13d5789e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "4.1.4+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-loot-api-v3",
          "version": {
            "requires": "3.0.17+8472aabc9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-menu-api-v1",
          "version": {
            "requires": "2.0.16+445199e59e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-message-api-v1",
          "version": {
            "requires": "7.0.8+bb2ed3f79e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-model-loading-api-v1",
          "version": {
            "requires": "8.0.17+306652609e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "6.3.3+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-object-builder-api-v1",
          "version": {
            "requires": "24.1.0+306652609e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-particles-v1",
          "version": {
            "requires": "5.0.18+35e09eec9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-permission-api-v1",
          "version": {
            "requires": "1.0.5+b8759c2f9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-recipe-api-v1",
          "version": {
            "requires": "9.0.21+5bc850709e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "7.1.0+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-renderer-api-v1",
          "version": {
            "requires": "14.1.4+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-renderer-indigo",
          "version": {
            "requires": "9.1.4+dfc0a2a19e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-rendering-fluids-v1",
          "version": {
            "requires": "6.0.4+2252655c9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-rendering-v1",
          "version": {
            "requires": "25.3.3+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-resource-conditions-api-v1",
          "version": {
            "requires": "6.1.0+0404dc439e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-resource-loader-v1",
          "version": {
            "requires": "2.0.13+60fb9d7f9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-screen-api-v1",
          "version": {
            "requires": "5.2.1+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-serialization-api-v1",
          "version": {
            "requires": "2.0.4+877e9f519e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-sound-api-v1",
          "version": {
            "requires": "2.0.5+76b071469e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-tag-api-v1",
          "version": {
            "requires": "2.1.4+33362aa29e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-transfer-api-v1",
          "version": {
            "requires": "8.0.13+d6727f829e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-transitive-access-wideners-v1",
          "version": {
            "requires": "8.1.4+3b084dff9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "internal",
          "version": {
            "requires": "0.159.0"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "3.3.20+5f5192e39e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "ffapi-fluid-types",
          "version": {
            "requires": "1.1.0+746500be9e"
          }
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "platform",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "forgified-fabric-api",
          "version": {
            "requires": "0.159.0+26.2+4.0.0"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-api-deprecated",
          "version": {
            "requires": "0.159.0+26.2+4.0.0"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-api-base",
          "version": {
            "requires": "2.0.4+d41ec0009e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-api-lookup-api-v1",
          "version": {
            "requires": "2.0.18+5f5192e39e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-biome-api-v1",
          "version": {
            "requires": "18.0.6+5f5192e39e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-block-api-v1",
          "version": {
            "requires": "3.0.3+12da5b389e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-block-getter-api-v2",
          "version": {
            "requires": "2.0.7+ec56b6019e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-client-gametest-api-v1",
          "version": {
            "requires": "6.0.1+3245a3939e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-command-api-v2",
          "version": {
            "requires": "3.1.0+df4186689e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-content-registries-v0",
          "version": {
            "requires": "11.3.2+3731f8bf9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-convention-tags-v2",
          "version": {
            "requires": "4.7.1+33362aa29e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-creative-tab-api-v1",
          "version": {
            "requires": "5.0.14+930083f69e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-data-attachment-api-v1",
          "version": {
            "requires": "2.2.18+203ddbf49e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-data-generation-api-v1",
          "version": {
            "requires": "25.5.1+3245a3939e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-debug-api-v1",
          "version": {
            "requires": "1.0.2+2b0337649e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-dimensions-v1",
          "version": {
            "requires": "5.1.12+df4186689e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-entity-events-v1",
          "version": {
            "requires": "5.0.5+306652609e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-events-interaction-v0",
          "version": {
            "requires": "5.2.7+df4186689e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-game-rule-api-v1",
          "version": {
            "requires": "4.0.8+46a6d00c9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-gametest-api-v1",
          "version": {
            "requires": "4.0.21+905131659e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-item-api-v1",
          "version": {
            "requires": "14.5.0+306652609e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-key-mapping-api-v1",
          "version": {
            "requires": "2.0.5+ce13d5789e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-lifecycle-events-v1",
          "version": {
            "requires": "4.1.4+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-loot-api-v3",
          "version": {
            "requires": "3.0.17+8472aabc9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-menu-api-v1",
          "version": {
            "requires": "2.0.16+445199e59e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-message-api-v1",
          "version": {
            "requires": "7.0.8+bb2ed3f79e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-model-loading-api-v1",
          "version": {
            "requires": "8.0.17+306652609e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-networking-api-v1",
          "version": {
            "requires": "6.3.3+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-object-builder-api-v1",
          "version": {
            "requires": "24.1.0+306652609e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-particles-v1",
          "version": {
            "requires": "5.0.18+35e09eec9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-permission-api-v1",
          "version": {
            "requires": "1.0.5+b8759c2f9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-recipe-api-v1",
          "version": {
            "requires": "9.0.21+5bc850709e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-registry-sync-v0",
          "version": {
            "requires": "7.1.0+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-renderer-api-v1",
          "version": {
            "requires": "14.1.4+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-renderer-indigo",
          "version": {
            "requires": "9.1.4+dfc0a2a19e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-rendering-fluids-v1",
          "version": {
            "requires": "6.0.4+2252655c9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-rendering-v1",
          "version": {
            "requires": "25.3.3+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-resource-conditions-api-v1",
          "version": {
            "requires": "6.1.0+0404dc439e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-resource-loader-v1",
          "version": {
            "requires": "2.0.13+60fb9d7f9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-screen-api-v1",
          "version": {
            "requires": "5.2.1+d89c76349e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-serialization-api-v1",
          "version": {
            "requires": "2.0.4+877e9f519e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-sound-api-v1",
          "version": {
            "requires": "2.0.5+76b071469e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-tag-api-v1",
          "version": {
            "requires": "2.1.4+33362aa29e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-transfer-api-v1",
          "version": {
            "requires": "8.0.13+d6727f829e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-transitive-access-wideners-v1",
          "version": {
            "requires": "8.1.4+3b084dff9e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "internal",
          "version": {
            "requires": "0.159.0"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "fabric-resource-loader-v0",
          "version": {
            "requires": "3.3.20+5f5192e39e"
          }
        },
        {
          "group": "org.sinytra.forgified-fabric-api",
          "module": "ffapi-fluid-types",
          "version": {
            "requires": "1.1.0+746500be9e"
          }
        }
      ]
    }
  ]
}
